# Generated by Django 4.1.7 on 2023-03-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0009_remove_categorie_type_alter_categorie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(choices=[('Al', 'Alimentaire'), ('Mb', 'Meuble'), ('Sn', 'Sanitaire'), ('Vs', 'Vaiselle'), ('Vt', 'Vetement'), ('Jx', 'Jouets'), ('Lg', 'Lige de Maison'), ('Bj', 'Bijoux'), ('Dc', 'Decor')], default='Al', max_length=50),
        ),
    ]
