# Generated by Django 4.1.7 on 2023-03-08 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0010_alter_categorie_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitC',
            fields=[
                ('produit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='magasin.produit')),
                ('Duree_emb', models.CharField(max_length=100)),
            ],
            bases=('magasin.produit',),
        ),
    ]
